In [1]:
import numpy as np

In [59]:
# part b

In [44]:
c1 = 10
c2 = 20
c3 = 30
c4 = 40

In [45]:
L = -(np.array([[-c1, c1, 0, 0, 0],
              [c1, -(c1+c2), c2, 0, 0],
              [0, c2, -(c2+c3), c3, 0],
              [0, 0, c3, -(c3+c4), c4],
              [0, 0, 0, c4, -c4]]))

In [46]:
L

array([[ 10, -10,   0,   0,   0],
       [-10,  30, -20,   0,   0],
       [  0, -20,  50, -30,   0],
       [  0,   0, -30,  70, -40],
       [  0,   0,   0, -40,  40]])

In [47]:
# part c

In [51]:
np.matmul(L, np.ones(5))

array([0., 0., 0., 0., 0.])

In [52]:
np.matmul(np.ones(5), L)

array([0., 0., 0., 0., 0.])

In [66]:
print("Eigen values = ", np.linalg.eigvals(L + L.T).round(10))
print("L + Ltranspose >= 0 is ", (np.linalg.eigvals(L + L.T).round(10).all()) >= 0)

Eigen values =  [219.07788625 114.62357503  51.43270015  -0.          14.86583856]
L + Ltranspose >= 0 is  True
